# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RedmineCli < Formula
  desc "CLI for interacting with the Redmine REST API"
  homepage "https://github.com/nbifrye/redmine-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nbifrye/redmine-cli/releases/download/v0.1.0/redmine-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "6d74407e72588f05e8e327151a8037197e5f649d9529a53111e34a79456bf532"

      define_method(:install) do
        bin.install "redmine"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nbifrye/redmine-cli/releases/download/v0.1.0/redmine-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "6ef76d622dfb592d83f0aae48ba5b22ce1b85339dd8ae7c6746e91e524bc9deb"

      define_method(:install) do
        bin.install "redmine"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nbifrye/redmine-cli/releases/download/v0.1.0/redmine-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "421d73827b37813426eef238d3bf1f44e33441c6ae14e48893fccfbffea1c663"
      define_method(:install) do
        bin.install "redmine"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nbifrye/redmine-cli/releases/download/v0.1.0/redmine-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "9e4459e54f35f061bca4f292a9e1128231d5afa8da151d7add5f56cad7aa6e5c"
      define_method(:install) do
        bin.install "redmine"
      end
    end
  end

  test do
    system "#{bin}/redmine", "--help"
  end
end
