# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RedmineCli < Formula
  desc "CLI for interacting with the Redmine REST API"
  homepage "https://github.com/nbifrye/redmine-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nbifrye/redmine-cli/releases/download/v0.2.0/redmine-cli_0.2.0_darwin_amd64.tar.gz"
      sha256 "3eef7f2d904c4fc14ef231353e6b3b59ffcc0662c84e2f70827fecb7637aa652"

      define_method(:install) do
        bin.install "redmine"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nbifrye/redmine-cli/releases/download/v0.2.0/redmine-cli_0.2.0_darwin_arm64.tar.gz"
      sha256 "d35c93b9c86a1e232201b3ce0a091bb23381e2f04991e30f33a1671820168957"

      define_method(:install) do
        bin.install "redmine"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nbifrye/redmine-cli/releases/download/v0.2.0/redmine-cli_0.2.0_linux_amd64.tar.gz"
      sha256 "01cb0f7b1812a217c1ca38f2ef09d7ed5ab73ccad20233eef1833d6e904872d7"
      define_method(:install) do
        bin.install "redmine"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nbifrye/redmine-cli/releases/download/v0.2.0/redmine-cli_0.2.0_linux_arm64.tar.gz"
      sha256 "4758c6702555e71d63cb19f3942ea1a3772ea28bc263d2eb904ed91ba1e4b924"
      define_method(:install) do
        bin.install "redmine"
      end
    end
  end

  test do
    system "#{bin}/redmine", "--help"
  end
end
